global using static System.ArgumentException;
global using static System.ArgumentNullException;
global using static System.ArgumentOutOfRangeException;
global using Ardalis.Specification;
global using ErrorOr;
global using FluentValidation;
global using LinkawyGenie.Common.Features;
global using LinkawyGenie.Common.Persistence;
global using Microsoft.EntityFrameworkCore;
global using Vogen;
